---
- name: configure winserver
  hosts: winserver1

  tasks:
    - name: Enable Features
      ansible.windows.win_feature:
        name: "{{ win_features }}"
        state: "{{ state }}"
        include_sub_features: yes
        include_management_tools: yes
      register: win_output

    - name: reboot server if required
      ansible.windows.win_reboot:
      when: win_output.reboot_required

    - name: Ensure directory exists
      ansible.windows.win_file:
        path: '{{ dir_path }}ansible_directory'
        state: directory
      when: state == "present"

    - name: Ensure directory does not exist
      ansible.windows.win_file:
        path: '{{ dir_path }}ansible_directory'
        state: absent
      when: state == "absent"