---
- name: Add rule
  hosts: panos1
  connection: local

  vars:
    provider:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - name: Ensure deps are avabilable
      # Ensure we have all the right requirements installed in this environment
      pip:
        name:
          - pan-python
          - xmltodict
          - requests
          - requests_toolbelt
          - pandevice
    # - name: show list of all interfaces
    #   paloaltonetworks.panos.panos_op:
    #     provider: '{{ provider }}'
    #     cmd: 'show interfaces all'
    #   register: output

    # - debug:
    #     msg: "{{ output }}"
    - name: Create first security rule
      paloaltonetworks.panos.panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'Prod SSH Inbound'
        source_zone: ['untrust']
        destination_zone: ['trust']
        source_ip: ['any']
        destination_ip: ['Prod-Instances']
        application: ['ssh']
        service: ['application-default']
        action: 'allow'
        tag_name: ['Prod']
        commit: false

    # - name: Create second security rule
    #   paloaltonetworks.panos.panos_security_rule:
    #     provider: '{{ device }}'
    #     rule_name: 'SI Inbound'
    #     source_zone: ['untrust']
    #     destination_zone: ['trust']
    #     source_ip: ['any']
    #     destination_ip: ['SI-Instances']
    #     application: ['ssh', 'mysql']
    #     service: ['application-default']
    #     action: 'allow'
    #     tag_name: ['SI']
    #     commit: false